services:
  system-design-platform:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: system-design-platform
    ports:
      - "${HOST_IP:-127.0.0.1}:${PORT:-8004}:80"
    restart: unless-stopped
